name: Build & Deploy
on: [push]
jobs:

  deploy:
    name: Deploy to digitalocean droplet
    runs-on: ubuntu-latest
    steps:
    - name: deploy data import cron jobs
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DATA_IMPORT_SSH_HOST }}
        key: ${{ secrets.DATA_IMPORT_SSH_KEY }}
        username: ${{ secrets.DATA_IMPORT_SSH_USERNAME }}
        script: |
            pm2 stop cron
            rm -rf BallerAnalytics
            git clone -b TempVercelFix git@github.com:cryptodeal/BallerAnalytics.git
            cp .env ./BallerAnalytics
            cp .env ./BallerAnalytics/web
            cp .env ./BallerAnalytics/packages/nba-api-ts
            cd BallerAnalytics
            pnpm install
            pnpm build
            pm2 start packages/nba-api-ts/dist/scripts/cron.js