name: Build & Deploy
on: [push]
jobs:

  deploy:
    name: Deploy to digitalocean droplet
    runs-on: ubuntu-latest
    steps:
    - name: deploy data import cron jobs
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DATA_IMPORT_SSH_HOST }}
        key: ${{ secrets.DATA_IMPORT_SSH_KEY }}
        username: ${{ secrets.DATA_IMPORT_SSH_USERNAME }}
        script: |
            curl -fsSL https://get.pnpm.io/install.sh | sh -
            rm -rf dataImport
            mkdir dataImport
            cd dataImport
            git clone git@github.com:cryptodeal/BallerAnalytics.git
            cd BallerAnalytics/packages/nba-api-ts
            pnpm i
            

