name: CI
on: push 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install pnpm
      run: curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm@6
    - name: Install modules
      run: pnpm install
    - name: Run prettier
      run: pnpm format
    - name: Run ESLint
      run: pnpm lint